topic_names: [ 
              [ /data_fusion/victim_fusion/hole_direction_alert , pandora_vision_msgs , HolesDirectionsVectorMsg ] ,
              [ /vision/hazmat_alert , pandora_vision_msgs , HazmatAlertsVectorMsg ] ,
             ]

  


